
name: build-and-push-master-to-cloud-run

on:
  push:
    branches: [ main ]

jobs:
  buildpush:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - uses: google-github-actions/setup-gcloud@main
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true
    
    - name: Configure Docker
      run: |
        gcloud auth configure-docker europe-docker.pkg.dev

    - name: Run docker build
      run: docker build --no-cache -t europe-docker.pkg.dev/superb-blend-305320/lex-prod-registry/lex_model_graphviz_api:latest .

    - name: Run docker push
      run: docker push europe-docker.pkg.dev/superb-blend-305320/lex-prod-registry/lex_model_graphviz_api:latest

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: lex-model-graphviz-api
        image: europe-docker.pkg.dev/superb-blend-305320/lex-prod-registry/lex_model_graphviz_api:latest
        region: europe-west3


